env:
    CIRRUS_CLONE_DEPTH: 1

linux_task:
    matrix:
        - name: alpine
          container: &step
              image: ghcr.io/fish-shell/fish-ci/alpine:latest
              memory: 4GB
        - name: bionic
          container:
              <<: *step
              image: ghcr.io/fish-shell/fish-ci/bionic:latest
        - name: bionic-asan-clang
          container:
              <<: *step
              image: ghcr.io/fish-shell/fish-ci/bionic-asan-clang:latest
        - name: bionic-tsan
          container:
              <<: *step
              image: ghcr.io/fish-shell/fish-ci/bionic-tsan:latest
        - name: bionic-tsan-clang
          container:
              <<: *step
              image: ghcr.io/fish-shell/fish-ci/bionic-tsan-clang:latest
        - name: centos7
          container:
              <<: *step
              image: ghcr.io/fish-shell/fish-ci/centos7:latest
        - name: centos8
          container:
              <<: *step
              image: ghcr.io/fish-shell/fish-ci/centos8:latest
        - name: focal-32bit
          container:
              <<: *step
              image: ghcr.io/fish-shell/fish-ci/focal-32bit:latest
        - name: xenial
          container:
              <<: *step
              image: ghcr.io/fish-shell/fish-ci/xenial:latest

    tests_script:
        # cirrus at times gives us 32 procs and 2 GB of RAM
        # Unrestriced parallelism results in OOM
        - lscpu || true
        - (cat /proc/meminfo | grep MemTotal) || true
        - mkdir build && cd build
        - cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCTEST_PARALLEL_LEVEL=6 ..
        - ninja -j 6 fish fish_tests
        - ninja fish_run_tests
