env:
    CIRRUS_CLONE_DEPTH: 1

task:
    matrix:
        - name: alpine
          container: { image: ghcr.io/fish-shell/fish-ci/alpine:latest }
        - name: bionic
          container: { image: ghcr.io/fish-shell/fish-ci/bionic:latest }
        - name: bionic-asan-clang
          container: { image: ghcr.io/fish-shell/fish-ci/bionic-asan-clang:latest }
        - name: bionic-tsan
          container: { image: ghcr.io/fish-shell/fish-ci/bionic-tsan:latest }
        - name: bionic-tsan-clang
          container: { image: ghcr.io/fish-shell/fish-ci/bionic-tsan-clang:latest }
        - name: centos7
          container: { image: ghcr.io/fish-shell/fish-ci/centos7:latest }
        - name: centos8
          container: { image: ghcr.io/fish-shell/fish-ci/centos8:latest }
        - name: focal-32bit
          container: { image: ghcr.io/fish-shell/fish-ci/focal-32bit:latest }
        - name: xenial
          container: { image: ghcr.io/fish-shell/fish-ci/xenial:latest }

    tests_script:
        - lscpu || true
        - (cat /proc/meminfo | grep MemTotal) || true
        - mkdir build && cd build
        # cirrus gives us 32 procs and 2 GB of RAM
        # Unrestriced parallelism results in OOM
        - cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCTEST_PARALLEL_LEVEL=4 ..
        - ninja -j 4 fish fish_tests
        - ninja fish_run_tests
