---
kind: pipeline
type: digitalocean
name: run-vagrant-tests

token:
    from_secret: DO_token

server:
    image: 120123183 # virtualbox-ubuntu-c-4-8gib-2
    size: c-4
    region: nyc1

platform:
    os: linux
    arch: amd64

steps:
    - &step
      name: freebsd-13-1-release
      commands:
          - ls /dev/vboxdrv
          - echo $${VAGRANT_DIR}
          - $${VAGRANT_DIR}/run_tests_in_box.sh $${DRONE_WORKSPACE} fish-freebsd-13-1-release
      devices:
          - name: vboxdrv
            path: /dev/vboxdrv

volumes:
    - name: vboxdrv
      host:
          name: vboxdrv
          path: /dev/vboxdrv
      path: /dev/vboxdrv

devices:
    - name: vboxdrv
      path: /dev/vboxdrv
