---
kind: pipeline
type: digitalocean
name: run-docker-tests

token:
    from_secret: DO_token

platform:
    os: linux
    arch: amd64

server:
    image: 120194041
    size: c-4
    region: nyc1

steps:
    - &docker-step
      name: alpine
      image: ridiculousfish/fish-shell-ci-runner:latest
      volumes:
          - name: dockersock
            path: /var/run/
      commands:
          - echo ${REGISTRY}
          - ./docker/docker_run_tests_ci.sh $${DOCKERIMAGE}
      environment: { DOCKERIMAGE: alpine }
      when:
          status:
              - failure
              - success
    - <<: *docker-step
      name: bionic-asan-clang
      environment: { DOCKERIMAGE: bionic-asan-clang }
    - <<: *docker-step
      name: bionic-tsan-clang
      environment: { DOCKERIMAGE: bionic-tsan-clang }
    - <<: *docker-step
      name: bionic-tsan
      environment: { DOCKERIMAGE: bionic-tsan }
    - <<: *docker-step
      name: bionic
      environment: { DOCKERIMAGE: bionic }
    - <<: *docker-step
      name: centos7
      environment: { DOCKERIMAGE: centos7 }
    - <<: *docker-step
      name: centos8
      environment: { DOCKERIMAGE: centos8 }
    - <<: *docker-step
      name: fedora
      environment: { DOCKERIMAGE: fedora }
    - <<: *docker-step
      name: focal-32bit
      environment: { DOCKERIMAGE: focal-32bit }
    - <<: *docker-step
      name: xenial
      environment: { DOCKERIMAGE: xenial }

    - &vagrant-step
      name: freebsd-13-1-release
      commands:
          - ls /dev/vboxdrv
          - ./vagrant/vagrant_run_in_docker.sh $${BOXNAME}
      environment: { BOXNAME: fish-freebsd-13-1-release }
      when:
          status:
              - failure
              - success

volumes:
    - name: dockersock
      host:
          path: /var/run/
