---
kind: pipeline
type: digitalocean
name: run-vagrant-tests

token:
    from_secret: DO_token

server:
    image: 120194041 # snapshot ID for fish-ci-virtualbox-1
    size: c-4
    region: nyc1

platform:
    os: linux
    arch: amd64

steps:
    - &step
      name: freebsd-13-1-release
      commands:
          - ls /dev/vboxdrv
          - ./vagrant/vagrant_run_in_docker.sh $${BOXNAME}
      environment: { BOXNAME: fish-freebsd-13-1-release }
